/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  aux_sym_attribute_value_token1 = 10,
  sym_entity = 11,
  anon_sym_SQUOTE = 12,
  anon_sym_DQUOTE = 13,
  aux_sym__quoted_attribute_value_inner_token1 = 14,
  sym_text = 15,
  sym__start_tag_name = 16,
  sym__script_start_tag_name = 17,
  sym__style_start_tag_name = 18,
  sym__end_tag_name = 19,
  sym_erroneous_end_tag_name = 20,
  sym__implicit_end_tag = 21,
  sym_raw_text = 22,
  sym_comment = 23,
  sym_jinja = 24,
  sym_document = 25,
  sym_doctype = 26,
  sym__node = 27,
  sym_element = 28,
  sym_script_element = 29,
  sym_style_element = 30,
  sym_start_tag = 31,
  sym_script_start_tag = 32,
  sym_style_start_tag = 33,
  sym_self_closing_tag = 34,
  sym_end_tag = 35,
  sym_erroneous_end_tag = 36,
  sym_attribute = 37,
  sym_attribute_value = 38,
  sym_quoted_attribute_value = 39,
  sym__quoted_attribute_value_inner = 40,
  aux_sym_document_repeat1 = 41,
  aux_sym_start_tag_repeat1 = 42,
  aux_sym_quoted_attribute_value_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [aux_sym_attribute_value_token1] = "attribute_value_token1",
  [sym_entity] = "entity",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__quoted_attribute_value_inner_token1] = "attribute_value",
  [sym_text] = "text",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_jinja] = "jinja",
  [sym_document] = "document",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_attribute_value] = "attribute_value",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym__quoted_attribute_value_inner] = "_quoted_attribute_value_inner",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_quoted_attribute_value_repeat1] = "quoted_attribute_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [aux_sym_attribute_value_token1] = aux_sym_attribute_value_token1,
  [sym_entity] = sym_entity,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__quoted_attribute_value_inner_token1] = sym_attribute_value,
  [sym_text] = sym_text,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_jinja] = sym_jinja,
  [sym_document] = sym_document,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_attribute_value] = sym_attribute_value,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym__quoted_attribute_value_inner] = sym__quoted_attribute_value_inner,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_quoted_attribute_value_repeat1] = aux_sym_quoted_attribute_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quoted_attribute_value_inner_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_jinja] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_attribute_value_inner] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 9,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 20,
  [25] = 10,
  [26] = 11,
  [27] = 12,
  [28] = 13,
  [29] = 14,
  [30] = 22,
  [31] = 17,
  [32] = 18,
  [33] = 23,
  [34] = 19,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 39,
  [41] = 38,
  [42] = 35,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 37,
  [51] = 51,
  [52] = 52,
  [53] = 44,
  [54] = 46,
  [55] = 43,
  [56] = 45,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 57,
  [62] = 62,
  [63] = 47,
  [64] = 64,
  [65] = 65,
  [66] = 65,
  [67] = 64,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 58,
  [72] = 59,
  [73] = 60,
  [74] = 62,
  [75] = 75,
  [76] = 76,
  [77] = 76,
  [78] = 78,
  [79] = 70,
  [80] = 80,
  [81] = 78,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 87,
  [89] = 89,
  [90] = 90,
  [91] = 83,
  [92] = 89,
  [93] = 84,
  [94] = 86,
  [95] = 85,
  [96] = 90,
};

static const TSCharacterRange sym_attribute_name_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'(', '.'}, {'0', ';'}, {'?', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 69,
        '&', 3,
        '\'', 68,
        '/', 5,
        '<', 22,
        '=', 25,
        '>', 20,
        'D', 8,
        'd', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '\'') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '\'') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(71);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '>') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(26);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(9);
      END_STATE();
    case 13:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '<') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(72);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_attribute_name);
      if ((!eof && set_contains(sym_attribute_name_character_set_1, 9, lookahead))) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if ((!eof && set_contains(sym_attribute_name_character_set_1, 9, lookahead)) ||
          lookahead == '/') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym__quoted_attribute_value_inner_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym__quoted_attribute_value_inner_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(72);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 15, .external_lex_state = 2},
  [2] = {.lex_state = 15, .external_lex_state = 3},
  [3] = {.lex_state = 15, .external_lex_state = 3},
  [4] = {.lex_state = 15, .external_lex_state = 3},
  [5] = {.lex_state = 15, .external_lex_state = 3},
  [6] = {.lex_state = 15, .external_lex_state = 3},
  [7] = {.lex_state = 15, .external_lex_state = 2},
  [8] = {.lex_state = 15, .external_lex_state = 2},
  [9] = {.lex_state = 15, .external_lex_state = 3},
  [10] = {.lex_state = 15, .external_lex_state = 2},
  [11] = {.lex_state = 15, .external_lex_state = 2},
  [12] = {.lex_state = 15, .external_lex_state = 2},
  [13] = {.lex_state = 15, .external_lex_state = 2},
  [14] = {.lex_state = 15, .external_lex_state = 2},
  [15] = {.lex_state = 15, .external_lex_state = 2},
  [16] = {.lex_state = 15, .external_lex_state = 3},
  [17] = {.lex_state = 15, .external_lex_state = 2},
  [18] = {.lex_state = 15, .external_lex_state = 2},
  [19] = {.lex_state = 15, .external_lex_state = 2},
  [20] = {.lex_state = 15, .external_lex_state = 3},
  [21] = {.lex_state = 15, .external_lex_state = 3},
  [22] = {.lex_state = 15, .external_lex_state = 3},
  [23] = {.lex_state = 15, .external_lex_state = 3},
  [24] = {.lex_state = 15, .external_lex_state = 2},
  [25] = {.lex_state = 15, .external_lex_state = 3},
  [26] = {.lex_state = 15, .external_lex_state = 3},
  [27] = {.lex_state = 15, .external_lex_state = 3},
  [28] = {.lex_state = 15, .external_lex_state = 3},
  [29] = {.lex_state = 15, .external_lex_state = 3},
  [30] = {.lex_state = 15, .external_lex_state = 2},
  [31] = {.lex_state = 15, .external_lex_state = 3},
  [32] = {.lex_state = 15, .external_lex_state = 3},
  [33] = {.lex_state = 15, .external_lex_state = 2},
  [34] = {.lex_state = 15, .external_lex_state = 3},
  [35] = {.lex_state = 1, .external_lex_state = 2},
  [36] = {.lex_state = 2, .external_lex_state = 2},
  [37] = {.lex_state = 4, .external_lex_state = 4},
  [38] = {.lex_state = 4, .external_lex_state = 4},
  [39] = {.lex_state = 4, .external_lex_state = 4},
  [40] = {.lex_state = 4, .external_lex_state = 4},
  [41] = {.lex_state = 4, .external_lex_state = 4},
  [42] = {.lex_state = 1, .external_lex_state = 2},
  [43] = {.lex_state = 2, .external_lex_state = 2},
  [44] = {.lex_state = 2, .external_lex_state = 2},
  [45] = {.lex_state = 2, .external_lex_state = 2},
  [46] = {.lex_state = 2, .external_lex_state = 2},
  [47] = {.lex_state = 4, .external_lex_state = 4},
  [48] = {.lex_state = 4, .external_lex_state = 2},
  [49] = {.lex_state = 4, .external_lex_state = 2},
  [50] = {.lex_state = 4, .external_lex_state = 2},
  [51] = {.lex_state = 4, .external_lex_state = 2},
  [52] = {.lex_state = 4, .external_lex_state = 2},
  [53] = {.lex_state = 2, .external_lex_state = 2},
  [54] = {.lex_state = 2, .external_lex_state = 2},
  [55] = {.lex_state = 2, .external_lex_state = 2},
  [56] = {.lex_state = 2, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 5},
  [58] = {.lex_state = 4, .external_lex_state = 4},
  [59] = {.lex_state = 4, .external_lex_state = 4},
  [60] = {.lex_state = 4, .external_lex_state = 4},
  [61] = {.lex_state = 0, .external_lex_state = 5},
  [62] = {.lex_state = 4, .external_lex_state = 4},
  [63] = {.lex_state = 4, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 6},
  [65] = {.lex_state = 0, .external_lex_state = 6},
  [66] = {.lex_state = 0, .external_lex_state = 6},
  [67] = {.lex_state = 0, .external_lex_state = 6},
  [68] = {.lex_state = 0, .external_lex_state = 6},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 7},
  [71] = {.lex_state = 4, .external_lex_state = 2},
  [72] = {.lex_state = 4, .external_lex_state = 2},
  [73] = {.lex_state = 4, .external_lex_state = 2},
  [74] = {.lex_state = 4, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 6},
  [76] = {.lex_state = 0, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 7},
  [80] = {.lex_state = 0, .external_lex_state = 6},
  [81] = {.lex_state = 0, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 13, .external_lex_state = 2},
  [85] = {.lex_state = 0, .external_lex_state = 8},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 0, .external_lex_state = 2},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 0, .external_lex_state = 9},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 2},
  [92] = {.lex_state = 0, .external_lex_state = 9},
  [93] = {.lex_state = 13, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 2},
  [95] = {.lex_state = 0, .external_lex_state = 8},
  [96] = {.lex_state = 0, .external_lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_jinja] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_document] = STATE(82),
    [sym_doctype] = STATE(7),
    [sym__node] = STATE(7),
    [sym_element] = STATE(7),
    [sym_script_element] = STATE(7),
    [sym_style_element] = STATE(7),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(67),
    [sym_style_start_tag] = STATE(66),
    [sym_self_closing_tag] = STATE(24),
    [sym_erroneous_end_tag] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_entity] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [sym_jinja] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(23), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(19), 1,
      sym_end_tag,
    STATE(20), 1,
      sym_self_closing_tag,
    STATE(64), 1,
      sym_script_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(21), 2,
      sym_entity,
      sym_text,
    STATE(5), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [45] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(20), 1,
      sym_self_closing_tag,
    STATE(27), 1,
      sym_end_tag,
    STATE(64), 1,
      sym_script_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(27), 2,
      sym_entity,
      sym_text,
    STATE(6), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [90] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(20), 1,
      sym_self_closing_tag,
    STATE(34), 1,
      sym_end_tag,
    STATE(64), 1,
      sym_script_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(3), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [135] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(12), 1,
      sym_end_tag,
    STATE(20), 1,
      sym_self_closing_tag,
    STATE(64), 1,
      sym_script_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(27), 2,
      sym_entity,
      sym_text,
    STATE(6), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [180] = 11,
    ACTIONS(37), 1,
      anon_sym_LT_BANG,
    ACTIONS(40), 1,
      anon_sym_LT,
    ACTIONS(43), 1,
      anon_sym_LT_SLASH,
    ACTIONS(49), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(20), 1,
      sym_self_closing_tag,
    STATE(64), 1,
      sym_script_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(46), 2,
      sym_entity,
      sym_text,
    STATE(6), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [222] = 11,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(67), 1,
      sym_script_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(53), 2,
      sym_entity,
      sym_text,
    STATE(8), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [264] = 11,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_LT_BANG,
    ACTIONS(58), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(67), 1,
      sym_script_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(64), 2,
      sym_entity,
      sym_text,
    STATE(8), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [306] = 3,
    ACTIONS(69), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(67), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [321] = 3,
    ACTIONS(73), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [336] = 3,
    ACTIONS(77), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(75), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [351] = 3,
    ACTIONS(81), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [366] = 3,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [381] = 3,
    ACTIONS(89), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [396] = 3,
    ACTIONS(69), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(67), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [411] = 3,
    ACTIONS(93), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(91), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [426] = 3,
    ACTIONS(97), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(95), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [441] = 3,
    ACTIONS(101), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(99), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [456] = 3,
    ACTIONS(105), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [471] = 3,
    ACTIONS(109), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(107), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [486] = 3,
    ACTIONS(113), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(111), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [501] = 3,
    ACTIONS(117), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(115), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [516] = 3,
    ACTIONS(121), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(119), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [531] = 3,
    ACTIONS(109), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(107), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [546] = 3,
    ACTIONS(73), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(71), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [561] = 3,
    ACTIONS(77), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(75), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [576] = 3,
    ACTIONS(81), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(79), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [591] = 3,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(83), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [606] = 3,
    ACTIONS(89), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(87), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [621] = 3,
    ACTIONS(117), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [636] = 3,
    ACTIONS(97), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(95), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [651] = 3,
    ACTIONS(101), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(99), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [666] = 3,
    ACTIONS(121), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(119), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [681] = 3,
    ACTIONS(105), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(103), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [696] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 2,
      sym_jinja,
      aux_sym_attribute_value_token1,
    STATE(59), 2,
      sym_attribute_value,
      sym_quoted_attribute_value,
  [714] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
    ACTIONS(131), 2,
      sym_jinja,
      aux_sym__quoted_attribute_value_inner_token1,
    STATE(36), 2,
      sym__quoted_attribute_value_inner,
      aux_sym_quoted_attribute_value_repeat1,
  [730] = 4,
    ACTIONS(136), 1,
      sym_attribute_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(134), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(37), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [746] = 5,
    ACTIONS(139), 1,
      anon_sym_GT,
    ACTIONS(141), 1,
      anon_sym_SLASH_GT,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    STATE(37), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [764] = 5,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(145), 1,
      anon_sym_GT,
    ACTIONS(147), 1,
      anon_sym_SLASH_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    STATE(41), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [782] = 5,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(145), 1,
      anon_sym_GT,
    ACTIONS(149), 1,
      anon_sym_SLASH_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    STATE(38), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [800] = 5,
    ACTIONS(139), 1,
      anon_sym_GT,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(151), 1,
      anon_sym_SLASH_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    STATE(37), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [818] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_SQUOTE,
    ACTIONS(157), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 2,
      sym_jinja,
      aux_sym_attribute_value_token1,
    STATE(72), 2,
      sym_attribute_value,
      sym_quoted_attribute_value,
  [836] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_SQUOTE,
    ACTIONS(161), 2,
      sym_jinja,
      aux_sym__quoted_attribute_value_inner_token1,
    STATE(36), 2,
      sym__quoted_attribute_value_inner,
      aux_sym_quoted_attribute_value_repeat1,
  [851] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_SQUOTE,
    ACTIONS(165), 2,
      sym_jinja,
      aux_sym__quoted_attribute_value_inner_token1,
    STATE(43), 2,
      sym__quoted_attribute_value_inner,
      aux_sym_quoted_attribute_value_repeat1,
  [866] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_DQUOTE,
    ACTIONS(161), 2,
      sym_jinja,
      aux_sym__quoted_attribute_value_inner_token1,
    STATE(36), 2,
      sym__quoted_attribute_value_inner,
      aux_sym_quoted_attribute_value_repeat1,
  [881] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
    ACTIONS(167), 2,
      sym_jinja,
      aux_sym__quoted_attribute_value_inner_token1,
    STATE(45), 2,
      sym__quoted_attribute_value_inner,
      aux_sym_quoted_attribute_value_repeat1,
  [896] = 3,
    ACTIONS(171), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(169), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [909] = 4,
    ACTIONS(173), 1,
      anon_sym_GT,
    ACTIONS(175), 1,
      sym_attribute_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [924] = 4,
    ACTIONS(175), 1,
      sym_attribute_name,
    ACTIONS(177), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    STATE(50), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [939] = 4,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(179), 1,
      sym_attribute_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    STATE(50), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [954] = 4,
    ACTIONS(175), 1,
      sym_attribute_name,
    ACTIONS(182), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    STATE(50), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [969] = 4,
    ACTIONS(175), 1,
      sym_attribute_name,
    ACTIONS(184), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    STATE(51), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [984] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_SQUOTE,
    ACTIONS(188), 2,
      sym_jinja,
      aux_sym__quoted_attribute_value_inner_token1,
    STATE(55), 2,
      sym__quoted_attribute_value_inner,
      aux_sym_quoted_attribute_value_repeat1,
  [999] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    ACTIONS(190), 2,
      sym_jinja,
      aux_sym__quoted_attribute_value_inner_token1,
    STATE(56), 2,
      sym__quoted_attribute_value_inner,
      aux_sym_quoted_attribute_value_repeat1,
  [1014] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_SQUOTE,
    ACTIONS(161), 2,
      sym_jinja,
      aux_sym__quoted_attribute_value_inner_token1,
    STATE(36), 2,
      sym__quoted_attribute_value_inner,
      aux_sym_quoted_attribute_value_repeat1,
  [1029] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    ACTIONS(161), 2,
      sym_jinja,
      aux_sym__quoted_attribute_value_inner_token1,
    STATE(36), 2,
      sym__quoted_attribute_value_inner,
      aux_sym_quoted_attribute_value_repeat1,
  [1044] = 4,
    ACTIONS(194), 1,
      sym__start_tag_name,
    ACTIONS(196), 1,
      sym__script_start_tag_name,
    ACTIONS(198), 1,
      sym__style_start_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1058] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(200), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1068] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(202), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1078] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(204), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1088] = 4,
    ACTIONS(196), 1,
      sym__script_start_tag_name,
    ACTIONS(198), 1,
      sym__style_start_tag_name,
    ACTIONS(206), 1,
      sym__start_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1102] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(208), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1112] = 3,
    ACTIONS(210), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(169), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1124] = 4,
    ACTIONS(212), 1,
      anon_sym_LT_SLASH,
    ACTIONS(214), 1,
      sym_raw_text,
    STATE(22), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1138] = 4,
    ACTIONS(212), 1,
      anon_sym_LT_SLASH,
    ACTIONS(216), 1,
      sym_raw_text,
    STATE(23), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1152] = 4,
    ACTIONS(218), 1,
      anon_sym_LT_SLASH,
    ACTIONS(220), 1,
      sym_raw_text,
    STATE(33), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1166] = 4,
    ACTIONS(218), 1,
      anon_sym_LT_SLASH,
    ACTIONS(222), 1,
      sym_raw_text,
    STATE(30), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1180] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(224), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1189] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(226), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1198] = 3,
    ACTIONS(228), 1,
      sym__end_tag_name,
    ACTIONS(230), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1209] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(200), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1218] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(202), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1227] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(204), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1236] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(208), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1245] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(232), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1254] = 3,
    ACTIONS(218), 1,
      anon_sym_LT_SLASH,
    STATE(13), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1265] = 3,
    ACTIONS(212), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1276] = 3,
    ACTIONS(212), 1,
      anon_sym_LT_SLASH,
    STATE(29), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1287] = 3,
    ACTIONS(230), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(234), 1,
      sym__end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1298] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
    ACTIONS(236), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1307] = 3,
    ACTIONS(218), 1,
      anon_sym_LT_SLASH,
    STATE(14), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1318] = 2,
    ACTIONS(238), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1326] = 2,
    ACTIONS(240), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1334] = 2,
    ACTIONS(242), 1,
      aux_sym_doctype_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1342] = 2,
    ACTIONS(228), 1,
      sym__end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1350] = 2,
    ACTIONS(244), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1358] = 2,
    ACTIONS(246), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1366] = 2,
    ACTIONS(248), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1374] = 2,
    ACTIONS(250), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1382] = 2,
    ACTIONS(252), 1,
      sym__doctype,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1390] = 2,
    ACTIONS(254), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1398] = 2,
    ACTIONS(230), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1406] = 2,
    ACTIONS(256), 1,
      aux_sym_doctype_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1414] = 2,
    ACTIONS(258), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1422] = 2,
    ACTIONS(234), 1,
      sym__end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
  [1430] = 2,
    ACTIONS(260), 1,
      sym__doctype,
    ACTIONS(3), 2,
      sym_comment,
      sym_jinja,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 222,
  [SMALL_STATE(8)] = 264,
  [SMALL_STATE(9)] = 306,
  [SMALL_STATE(10)] = 321,
  [SMALL_STATE(11)] = 336,
  [SMALL_STATE(12)] = 351,
  [SMALL_STATE(13)] = 366,
  [SMALL_STATE(14)] = 381,
  [SMALL_STATE(15)] = 396,
  [SMALL_STATE(16)] = 411,
  [SMALL_STATE(17)] = 426,
  [SMALL_STATE(18)] = 441,
  [SMALL_STATE(19)] = 456,
  [SMALL_STATE(20)] = 471,
  [SMALL_STATE(21)] = 486,
  [SMALL_STATE(22)] = 501,
  [SMALL_STATE(23)] = 516,
  [SMALL_STATE(24)] = 531,
  [SMALL_STATE(25)] = 546,
  [SMALL_STATE(26)] = 561,
  [SMALL_STATE(27)] = 576,
  [SMALL_STATE(28)] = 591,
  [SMALL_STATE(29)] = 606,
  [SMALL_STATE(30)] = 621,
  [SMALL_STATE(31)] = 636,
  [SMALL_STATE(32)] = 651,
  [SMALL_STATE(33)] = 666,
  [SMALL_STATE(34)] = 681,
  [SMALL_STATE(35)] = 696,
  [SMALL_STATE(36)] = 714,
  [SMALL_STATE(37)] = 730,
  [SMALL_STATE(38)] = 746,
  [SMALL_STATE(39)] = 764,
  [SMALL_STATE(40)] = 782,
  [SMALL_STATE(41)] = 800,
  [SMALL_STATE(42)] = 818,
  [SMALL_STATE(43)] = 836,
  [SMALL_STATE(44)] = 851,
  [SMALL_STATE(45)] = 866,
  [SMALL_STATE(46)] = 881,
  [SMALL_STATE(47)] = 896,
  [SMALL_STATE(48)] = 909,
  [SMALL_STATE(49)] = 924,
  [SMALL_STATE(50)] = 939,
  [SMALL_STATE(51)] = 954,
  [SMALL_STATE(52)] = 969,
  [SMALL_STATE(53)] = 984,
  [SMALL_STATE(54)] = 999,
  [SMALL_STATE(55)] = 1014,
  [SMALL_STATE(56)] = 1029,
  [SMALL_STATE(57)] = 1044,
  [SMALL_STATE(58)] = 1058,
  [SMALL_STATE(59)] = 1068,
  [SMALL_STATE(60)] = 1078,
  [SMALL_STATE(61)] = 1088,
  [SMALL_STATE(62)] = 1102,
  [SMALL_STATE(63)] = 1112,
  [SMALL_STATE(64)] = 1124,
  [SMALL_STATE(65)] = 1138,
  [SMALL_STATE(66)] = 1152,
  [SMALL_STATE(67)] = 1166,
  [SMALL_STATE(68)] = 1180,
  [SMALL_STATE(69)] = 1189,
  [SMALL_STATE(70)] = 1198,
  [SMALL_STATE(71)] = 1209,
  [SMALL_STATE(72)] = 1218,
  [SMALL_STATE(73)] = 1227,
  [SMALL_STATE(74)] = 1236,
  [SMALL_STATE(75)] = 1245,
  [SMALL_STATE(76)] = 1254,
  [SMALL_STATE(77)] = 1265,
  [SMALL_STATE(78)] = 1276,
  [SMALL_STATE(79)] = 1287,
  [SMALL_STATE(80)] = 1298,
  [SMALL_STATE(81)] = 1307,
  [SMALL_STATE(82)] = 1318,
  [SMALL_STATE(83)] = 1326,
  [SMALL_STATE(84)] = 1334,
  [SMALL_STATE(85)] = 1342,
  [SMALL_STATE(86)] = 1350,
  [SMALL_STATE(87)] = 1358,
  [SMALL_STATE(88)] = 1366,
  [SMALL_STATE(89)] = 1374,
  [SMALL_STATE(90)] = 1382,
  [SMALL_STATE(91)] = 1390,
  [SMALL_STATE(92)] = 1398,
  [SMALL_STATE(93)] = 1406,
  [SMALL_STATE(94)] = 1414,
  [SMALL_STATE(95)] = 1422,
  [SMALL_STATE(96)] = 1430,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
  ts_external_token_jinja = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_jinja] = sym_jinja,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_jinja] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
    [ts_external_token_jinja] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_jinja] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_jinja] = true,
  },
  [5] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_jinja] = true,
  },
  [6] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_jinja] = true,
  },
  [7] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_jinja] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_jinja] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_jinja] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "html",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 23,
      .patch_version = 2,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
